/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
    presets: [require("nativewind/preset")],
    theme: {
        extend: {
            colors: {
                "tertiary-fixed": "#e2e2e2",
                "surface-bright": "#2e3a49",
                "on-secondary-fixed": "#1a1c1c",
                "on-tertiary-fixed-variant": "#454747",
                "on-secondary-fixed-variant": "#464747",
                "on-tertiary-container": "#8c8d8d",
                "inverse-surface": "#d7e3f7",
                "surface-container": "#14202e",
                "surface-container-lowest": "#030f1c",
                "on-error": "#690005",
                "on-primary-fixed": "#001b3e",
                "surface-variant": "#2a3644",
                "on-surface": "#d7e3f7",
                "secondary-fixed-dim": "#c6c6c6",
                "tertiary-container": "#242626",
                "surface-tint": "#a9c7ff",
                "on-tertiary-fixed": "#1a1c1c",
                "inverse-on-surface": "#253140",
                "outline": "#8e9196",
                "outline-variant": "#44474c",
                "secondary": "#c6c6c6",
                "secondary-fixed": "#e3e2e2",
                "on-secondary-container": "#b8b8b8",
                "on-surface-variant": "#c4c6cc",
                "on-primary": "#003064",
                "primary-fixed-dim": "#a9c7ff",
                "surface-container-low": "#101c2a",
                "surface-dim": "#081421",
                "surface": "#081421",
                "on-error-container": "#ffdad6",
                "background": "#081421",
                "surface-container-highest": "#2a3644",
                "error": "#ffb4ab",
                "primary": "#a9c7ff",
                "tertiary": "#c6c6c7",
                "on-primary-fixed-variant": "#00468c",
                "tertiary-fixed-dim": "#c6c6c7",
                "on-secondary": "#2f3131",
                "on-primary-container": "#418df5",
                "on-tertiary": "#2f3131",
                "primary-fixed": "#d6e3ff",
                "surface-container-high": "#1f2b39",
                "primary-container": "#002551",
                "error-container": "#93000a",
                "on-background": "#d7e3f7",
                "secondary-container": "#484949",
                "inverse-primary": "#005db8"
            },
            fontFamily: {
                "headline": ["SpaceGrotesk", "sans-serif"],
                "body": ["Manrope", "sans-serif"],
                "label": ["PlusJakartaSans", "sans-serif"]
            }
        }
    },
    plugins: [],
}
